version: 0.0
os: linux

files:
    - source: /
      destination: .
      overwrite: yes

permissions:
    - object: ./deploy.sh
      owner: ec2-user
      group: ec2-user
      mode: 755
      type:
          - file

hooks:
    ApplicationStart:
        - location: ./deploy.sh
          timeout: 60
          runas: ec2-user
