spring:
  config:
    activate.on-profile: test
  jpa:
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
      show_log: true
      format_sql: true
    properties:
      hibernate:
        default_batch_fetch_size: 100

storage:
  datasource:
    core:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:testdb;MODE=MySQL;
      username: sa
      password:
      pool-name: core-db-pool
      data-source-properties:
        rewriteBatchedStatements: true

---

spring:
  config:
    activate.on-profile: local
  jpa:
    open-in-view: false
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
      show_log: true
      format_sql: true
    properties:
      hibernate:
        default_batch_fetch_size: 100
  batch:
    jdbc:
      initialize-schema: never
    job:
      enabled: false


storage:
  datasource:
    core:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url:
      username:
      password:
      maximum-pool-size: 5
      connection-timeout: 1100
      keepalive-time: 30000
      validation-timeout: 1000
      max-lifetime: 600000
      pool-name: core-db-pool
      data-source-properties:
        socketTimeout: 3000
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false
---

spring:
  config:
    activate.on-profile: prod
  jpa:
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
      show_log: true
      format_sql: true
    properties:
      hibernate:
        default_batch_fetch_size: 100
  batch:
    jdbc:
      initialize-schema: never
    job:
      enabled: false

storage:
  datasource:
    core:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://hanni.cfacertspqbw.ap-northeast-2.rds.amazonaws.com:3306/hanni
      username: admin
      password: Tpxhvm1234!!
      maximum-pool-size: 5
      connection-timeout: 1100
      keepalive-time: 30000
      validation-timeout: 1000
      max-lifetime: 600000
      pool-name: core-db-pool
      data-source-properties:
        socketTimeout: 3000
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false
---