logging:
  level:
    root: INFO  # 기본 로그 레벨 설정

monikit:
    logging:
        detailedLogging: true
        slowQueryThresholdMs: 1000
        criticalQueryThresholdMs: 5000
        datasourceLoggingEnabled: true
        filtersEnabled: true
        traceEnabled: true
        interceptorsEnabled: true
    metrics:
        metricsEnabled: true

---

spring:
  config:
    activate:
      on-profile: local

logging:
  config: classpath:logback-local.xml  # 로컬 환경에서 사용


monikit:
    logging:
        detailedLogging: true
        slowQueryThresholdMs: 1000
        criticalQueryThresholdMs: 5000
        datasourceLoggingEnabled: true
        filtersEnabled: true
        traceEnabled: true
        interceptorsEnabled: true
    metrics:
        metricsEnabled: true


---

spring:
  config:
    activate:
      on-profile: prod

logging:
  config: classpath:logback-prod.xml  # 프로덕션 환경에서 사용


monikit:
    logging:
        detailedLogging: true
        slowQueryThresholdMs: 1000
        criticalQueryThresholdMs: 5000
        datasourceLoggingEnabled: true
        filtersEnabled: true
        traceEnabled: true
        interceptorsEnabled: true
    metrics:
        metricsEnabled: true
